* Goals
** Have version control of webpages
** Use Franklin.jl for structure and deployment
** Use Markown for markup
** Use Emacs with Markdown or Org-Mode for editing markdown documents
** Or find a suitable alternative for creating correctly formatted 
** Use Magit for version commands/control
* Text/Images/Topics/Categories on the Webpage
** Picture of me  should be resized not be so dominant.
** Research Reports
*** analysis_population_deviations.tex
    and analysis_population_deviations.pdf
    written on Feb 22 2022, in LaTeX, but there is an html export of the
    document.
    Didn't work!
    This document analysis_population_deviations.html appears to only
    be the first section of the document, not the full document.  Some
    LaTeX macros did not translate, e.g. \today

    But there is a version dated Nov 23 2022 of
    analysis_population_deviations.org
    which may have been the original, exported to the LaTeX version,

    On <2023-10-16 Mon> I converted the master document
    analysis_population_deviations.org to Markdown with
    pandoc --from org --to markdown analysis_population_deviations.org
    > analysis_population_deviations.md
*** The conversion is pretty good, but needs some additional help.
**** The org directives #+PROPERTY:, #+STARTUP:, #+TAGS: got translated as code
**** However, the #+OPTIONS: got ignored and not passed to the .md
**** The org directives #+TITLE:,  #+AUTHOR:, #+EMAIL:, #+DATE:  were ignored.
**** Needed to add Title and Author and Email, following the suggestions at
https://stackoverflow.com/questions/17097894/markdown-tag-for-document-title
**** Need to change \' to just '
**** Change the citations to \citep{name}
**** Need to totally add the References transcribing from bibtex to Franklin format
https://franklinjl.org/syntax/divs-commands/#references
**** Experiments on <2023-10-17 Tue> with \cite{}, \citep{}, \bibitem{} etc.
didn't seem to get transcribed into HTML, etc.  Why not?
**** It seems that the Analysis Population Deviations document is complex,
with sections, titles, authors, some math, some code samples, some
figures, and some references.  This seems to be more complex than Markdown seems to be
able to handle easily, at least from a translated/transfromed
source. Maybe if I started a Markdown documnte from scratch it would
compose better.
**** So I am going to try the following:  an "Executive Summary" in Markdown,
with full document in PDF as a link.
**** DONE I was able to get this edited and successfully pushed to github
CLOSED: [2023-10-18 Wed 10:59]
- CLOSING NOTE [2023-10-18 Wed 10:59] \\
  The notes about git, github and magit in programming.org for tips
  about pushing to sdunbarne.github.io
*** Need to figure out a way to put a Table of Contents on the Research Reports page
to handle additional reports.
** Talks
*** Which talk about gerrymandering?  Most recent given to LPS?
** Julia Exercises
*** Tranlate to Markdown
** Check what I used to have on UNL website
   How to check, because ssh/remote access is so difficult?
